# محاسبات ماتریسی

در این تمرین می‌خواهیم عملیات‌های ماتریسی ساده را با کتاب‌خانه numpy تمرین کنیم.

برای شروع ماتریس‌های زیر را تعریف می‌کنیم:

$$
A = 
\left(\begin{array}{cc} 
1 & 2\\
5 & -2
\end{array}\right)
$$ 

$$
B = 
\left(\begin{array}{cc} 
-3 & 0\\
4 & 5
\end{array}\right)
$$ 

$$
C = 
\left(\begin{array}{cc} 
4 & 25\\
-\frac{1}{2} & -3
\end{array}\right)
$$ 

در این تمرین می‌خواهیم خروجی رابطه زیر را حساب کنیم:

$$  M = AC^{-1} + B^{T} + 3I  $$

که $I$ ماتریس همانی $ 2*2 $ است.

برای شروع، چهار ماتریس مورد نیاز را تعریف می‌کنیم:

In [2]:
import numpy as np

In [3]:
# Define A
A = np.array([[1,2],[5,-2]])

In [4]:
# Define B
B = np.array([[-3,0],[4,5]])

In [6]:
# Define C
C = np.array([[4,25],[-0.5,-3]])

In [9]:
# Define I
I = np.identity(2)
print(A, B, C, I, sep="\n-----\n")

[[ 1  2]
 [ 5 -2]]
-----
[[-3  0]
 [ 4  5]]
-----
[[ 4.  25. ]
 [-0.5 -3. ]]
-----
[[1. 0.]
 [0. 1.]]


حال باید مقدار وارون ماتریس $C$ را حساب کنیم و آن را در متغیر $C\_inv$ بریزیم:

In [12]:
# Calculate C_inv
C_inv = np.linalg.inv(C)
print(C_inv)

[[ -6. -50.]
 [  1.   8.]]


حال مقدار $ AC^{-1} $ را حساب می‌کنیم و در متغیر D می‌ریزیم:

In [13]:
# Calculate D
D = np.dot(A, C_inv)
print(C)

[[ 4.  25. ]
 [-0.5 -3. ]]


حال مقدار $ B^{T} $ را حساب می‌کنیم و در متغیر $ B\_T $ می‌ریزیم.

In [14]:
# Calculate B_T
B_T = B.T
print(B_T)

[[-3  4]
 [ 0  5]]


در انتها، مقدار نهایی $ M $ را حساب می‌کنیم.

In [11]:
# Calculate M
M = 

In [ ]:
print(M)

با اجرای دستور زیر، آرایه‌ها را ذخیره کنید تا پاسخ‌های‌تان ارزیابی شود.

In [ ]:
np.savez("answers.npz",C_inv = C_inv,D = D,B_T = B_T,M = M)