این دفترچه تنها جهت تمرین در کنار مطالعه‌ی درس‌نامه اضافه شده است.

In [1]:
import numpy as np

In [9]:
i = np.identity(3)
b = i == 0
print(i[b].shape)

(6,)


In [12]:
x = np.full((3, 3), 8)

In [14]:
print(np.dot(i, x))

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
